#支付账户数据源
payment-account:
  datasource:
    url: jdbc:mysql://106.14.15.55:3306/test1?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

#日志
logging:
  config: classpath:logback-spring.xml

#多环境
spring:
  profiles:
    active: local